### ISSUE TITLE
Create endpoint to batch upload projects from file upload

### ISSUE THREAD

**Issue by AJLiu** [HackGT/ballot#30]
~~Take a look at the metric data exported from devpost from healthtech and from hackgt 4. Notice that there are some prizes that are a little weird, i.e. which track that you're on for healthtech is a separate column, and all of the mlh prizes for hackgt are a separate column. https://drive.google.com/drive/u/0/folders/1nZShJ-rrYq-F7TDW68vP1Jl0FDzXuYdK~~

~~upload a devpost submission metric file (likely through graphql?) to automatically create a bunch of projects in the database. Look into Sequelize transact api for making batch sql queries.~~

**See update below

**Comment by kexin-zhang** [comment]
Hi! Suggestion -- file uploads aren't common in GraphQL, since GraphQL is more for querying/updating data. I think it may make more sense/be easier to have a separate REST endpoint to handle uploading a csv.

**Comment by AJLiu** [comment]
Update on requirement - we won't be using any of the Devpost CSV files, rather we'll be sending out a google form and using that to build a csv to upload.
This CSV will encode the following information - Devpost link, Project name, Prizes (categories), and Table location.

We'll want a second endpoint that we'll use to assign judges in batch. The interface with the model already exists as Ballots.batchCreate, we just need to be able to upload a CSV and call that.
