### ISSUE TITLE
Premade judging accounts, with noted specialties

### ISSUE THREAD

**Issue by joel99** [HackGT/ballot#72]
We try to recruit judges with expertises, it'd be nice to
- operationally, have accounts premade for them, sent to their contact emails
- have epicenter note which judges have which specialties, and highlight projects with keywords for their specialties

**Comment by NameThatFollows** [comment]
Devpost has a field when submitting called "Built With." Do you want to use that?

**Comment by joel99** [comment]
Yeah, probably use that, search keywords in description, etc. also useful
for visualizations
